# Generated by Django 5.0.6 on 2024-05-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_alter_post_author_alter_follow_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default='default.mp4', upload_to='post_videos'),
        ),
    ]
