# Generated by Django 5.0.6 on 2024-05-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_alter_post_image_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='cover_pics'),
        ),
    ]
