# Generated by Django 5.0.6 on 2024-05-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0008_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='like',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='share',
        ),
    ]
