# Generated by Django 5.0.6 on 2024-05-31 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0012_alter_post_image_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='shared_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shared_post', to='myuser.post'),
            preserve_default=False,
        ),
    ]
